### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by lugia19** [elevenlabs/elevenlabs-docs#10]
Path: /api-reference/history

Only the python code reflects the changes made when pagination was added. 
The description of the endpoint itself is lacking the "page_size" and "start_after_history_item_id" query parameters, and the description of the response is missing the "last_history_item_id" and "has_more" values alongside the "history" array.

**Comment by limo1996** [comment]
Noted

**Comment by limo1996** [comment]
Thanks:)

**Comment by limo1996** [comment]
Done. curl endpoint is not doing pagination but that's fine, it works anyway..
