### ISSUE TITLE
API Documentation does not explain how to set a specific language

### ISSUE THREAD

**Issue by marcopeg** [elevenlabs/elevenlabs-docs#105]
Path: /api-reference/text-to-speech

I'm translating Swedish rows, it works ok most of the time, but if I have a sentence like "kapite 1" it will produce german accent.
How can I set the specific language that I desire to produce?

Same goes if I need to play a single word (vocabulary app for instance)

**Comment by louisjoecodes** [comment]
Turbo v2.5 now supports a `language_code` request paramater
