### ISSUE TITLE
Docs wrongly referencing specifying pitch and speaking rate

### ISSUE THREAD

**Issue by lugia19** [elevenlabs/elevenlabs-docs#109]
Path: /api-reference/python-text-to-speech-guide

"You can also customize aspects like pitch and speaking rate using VoiceSettings" is just wrong and should be fixed.
The code block is also wrong:
```python
from elevenlabs import VoiceSettings  
  
settings = VoiceSettings(speaking_rate=0.8)  
audio = generate("Welcome to our podcast!", voice="Amy", settings=settings)
```

**Comment by louisjoecodes** [comment]
Documentation updated thanks!
