### ISSUE TITLE
Mention lack of support for SSML tags on websockets

### ISSUE THREAD

**Issue by lugia19** [elevenlabs/elevenlabs-docs#110]
Path: /api-reference/websockets

SSML tags do not currently work when streaming with websockets. Mentioning it here (or on the prompting page) would be good.

**Comment by RamanSB** [comment]
Has there been any update on this issue since? I am using websocket, the team has told me to add the `enable_ssml_parsing` parameter. But it doesn't work, I'd like to get a proper update on this matter from the 11 labs team.

**Comment by louisjoecodes** [comment]
Hey apologies for the delay - can you confirm this is still an issue?

https://elevenlabs.io/docs/api-reference/websockets#query-parameters

**Comment by lugia19** [comment]
I can confirm that it's no longer relevant as support for SSML tags was added.
