### ISSUE TITLE
SSML Natural Pause Issue

### ISSUE THREAD

**Issue by RamanSB** [elevenlabs/elevenlabs-docs#130]
As per the [prompting documentation](https://elevenlabs.io/docs/speech-synthesis/prompting) we have been instructed that natural pauses can be implemented via <break time="Xs" /> where X is between 0.0 and 3.0.

I've generated text: **It's in times like these that our strength truly shines through `<break time="0.5s" />` and it seems you've been flexing those muscles quite a bit.**

But rather than actually pausing, the speaker is saying "Break time 05" why is this happening?

Issues remains w/ both models:
- eleven_multilingual_v2
- eleven_turbo_v2.

**Comment by vladislav887139** [comment]
Interesting

**Comment by dosstx** [comment]
Does not happen to me.

**Comment by RamanSB** [comment]
Very strange, do you mind sharing your set up please, are you using a Websocket connection to stream the response? What Audio Model are you using. 

The breaks work for me within the 11 Labs within the GUI but does not work programatically within my codebase, it doesn't make sense.

**Comment by nikhilpictory** [comment]
It is happening with me also! i am using websocket communication! any update here?

**Comment by louisjoecodes** [comment]
It’s possible that when chunking text for WebSockets, the <break> tags may be spoken out. For example, sending a chunk like "It's in times like these<break time='0.5s' />" could result in "break time" being spoken if the text is split there. Ensure your text is chunked properly to avoid this. Adjusting the chunking function should fix this.
