### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by Yelenys** [elevenlabs/elevenlabs-docs#142]
Path: /speech-synthesis/feedback

The text-to-speech feature, in Romanian, often pronounces Romanian words as if they were English. 
Sometimes the accent sounds a bit Spanish (?).
I used a lot of quota points to just have one qualitative recording, and am still struggling with it, so no satisfying result until now.
Bringing smaller correctly pronounced recordings together, by separately regenerating the wrong ones once (and sometimes over and over) again, doesn't help either, because with each new voice generation, the same voice sounds different, has a different pitch etc, so a botched version containing multiple same-voice generations sounds unnatural, to say the least. 
And especially when the text is longer, it's a nightmare trying to correct so many wrongly pronounced words or phrases.
It would probably be more helpful to be able to select a single language in the language drop-down of the language model section, rather than the whole model comprising a long list of languages altogether, especially when the original text is in one language only. 
Another suggestion - to include a specifications/requirements section, separate from the text-to-speech entry field, that would describe any details on how the text should be pronounced, intonation, other relevant details. I say "separate field", because these instructions shouldn't be pronounced as well, they are only there as job description, to help design a speech that is intended. These requirements shouldn't be subtracted from the quota as well, as they are not part of the text that is to be converted to speech. 
Also it would be more correctly if quota points were subtracted at download of the satisfying version of the generated speech, and not at the moment the speech is being generated (which often happens to be far from flawless, and will need multiple or endless takes until it sounds right).

**Comment by louisjoecodes** [comment]
Hi, please see: [Prompting](https://elevenlabs.io/docs/speech-synthesis/prompting)
I hope this helps with your next recordings!
