### ISSUE TITLE
Pronunciation Dictionaries "Add from file" Documentation is not under the Projects heading

### ISSUE THREAD

**Issue by rjmcf** [elevenlabs/elevenlabs-docs#144]
Path: /api-reference/add-from-file

The other API endpoint assocaiated with Pronunciation Dictionaries (at /api-reference/update-pronunciation-dictionaries) appears under the Projects heading. I believe that the "Add from file" endpoint should appear under the same heading.

![image](https://github.com/elevenlabs/elevenlabs-docs/assets/9089935/1af8e3fe-9714-4197-85a8-5bbf8f71dc1f)

**Comment by louisjoecodes** [comment]
Thanks for flagging, I propose we keep that route under projects for now as this route is specific to projects.
