### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by murdoch31** [elevenlabs/elevenlabs-docs#149]
Path: /troubleshooting/overview   
[ElevenLabs_2024-01-25T10_00_15_xella voice kloon_ivc_s50_sb75_se24_b_m2.mp3.zip](https://github.com/elevenlabs/elevenlabs-docs/files/14050052/ElevenLabs_2024-01-25T10_00_15_xella.voice.kloon_ivc_s50_sb75_se24_b_m2.mp3.zip)
When I generate speech through speech or even by text there is a background noise. What do I do wrong?

**Comment by louisjoecodes** [comment]
Hi has this been resolved? Curious to know which voice you are using here so I can check this on my side.
