### ISSUE TITLE
I need Ukrainian language for voice cloning

### ISSUE THREAD

**Issue by OBOZ-TV** [elevenlabs/elevenlabs-docs#152]
Path: /troubleshooting/overview Please add the Ukrainian language for voice cloning, because I will have to leave your service and I was hoping that our cooperation would be fruitful.

**Comment by louisjoecodes** [comment]
Feel free to try these voices:

![Screenshot 2024-10-21 at 12 43 21](https://github.com/user-attachments/assets/ca8b4676-5a20-40ba-9c4b-028d2e8d98b7)
