### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by CodeBooster97** [elevenlabs/elevenlabs-docs#153]
Path: /api-reference/add-voice

No max file-size and file limits

**Comment by louisjoecodes** [comment]
Hey @CodeBooster97 feel free to clarify your issue.

**Comment by CodeBooster97** [comment]
https://elevenlabs.io/docs/api-reference/add-voice#add-voice

Your API has limits about the maximum file-size I can upload and the maximum number of files. 
Thes limits are not specified in the documentation.
