### ISSUE TITLE
I would like to understand how to add a language to the list of available languages.

### ISSUE THREAD

**Issue by tonymattina** [elevenlabs/elevenlabs-docs#158]
I have substantial audio and transcriptions of a Native language of North America and would like to understand how to build an acoustic model. Thank you.

**Comment by louisjoecodes** [comment]
Hi @tonymattina happy to help here, would need more context to understand the issue?

**Comment by louisjoecodes** [comment]
This should be useful [Overview](https://elevenlabs.io/docs/voices/voice-lab/overview)

**Comment by tonymattina** [comment]
I am traveling overseas. Will reply when I'm back. Thanks.

**Comment by tonymattina** [comment]
Hello Louis J.,
A while back I contacted elevenlabs hoping to get help working with
speech-to-text. Languages are being added to Google translate (Sicilian,
Lombard, and a host of others), so why not an American Indian language of
the Pacific Northwest. Your recent e-mail message has pleasantly surprised
me and made me a bit hopeful.

I have studied Colville-Okanagan since 1968, and have documented it: a
dictionary, many narratives, a grammar, exercises aplenty. etc. These
materials are all in the pages I maintain, MELTR.org, strictly an
"academic" site where I sell nothing, but offer language data. Nobody pays
me, I do it for the love of the language and the folks seem to appreciate
it. I have 25 thousand hits a month, I zoom with other students of the
language (native and not) at their request. I am a linguist, but I have
managed to learn enough javascript to code what I call "interactive
listening" apps. I have made mock videos of narratives long and short; I
have made exercises to help folks study and learn the language.

I am not very comfortable with github, even though I have a repository
(that I don't manage well). I have been looking into pytorch, but I need
some guidance. Not ready to interrupt what I am doing to plunge into
something new, at my age. If I hear back from you I will see what help I
can get with github. I know there are lots of tutorials on youtube. Feel
free to suggest ways to proceed.

I do hope elvenlabs is serious in its interest to work with
Colville-Okanagan, a Salish language of Washington State and British
Columbia. Please check out my work I have posted at MELTR.org. and let me
know.

I look forward to your reply.
Tony Mattina
