### ISSUE TITLE
Clarify quality differences for websocket and POST

### ISSUE THREAD

**Issue by BjoernRave** [elevenlabs/elevenlabs-docs#162]
I need the word level timestamps which are currently only available through the websocket endpoint, which is a little inconvenient.

However I since I want the highest possible quality for the audio I am not sure if I should use the POST endpoint + Whisper to get the timestamps or if I should use the websocket endpoint and just send the whole text at once and the audio quality will be the same.

It would be nice to know if there are quality differences between using websocket and POST

**Comment by louisjoecodes** [comment]
Hey @BjoernRave check out this [example](https://github.com/louisjoecodes/elevenlabs-websockets-demo) project. We have updated our [WebSocket]([How to use websocket](https://elevenlabs.io/docs/api-reference/how-to-use-websocket)) documentation to go into detail about trade-offs etc.

Feel free to re-open if you need any more help!
