### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by goohuh** [elevenlabs/elevenlabs-docs#175]
Path: /voicelab/pre-made-voices

It seems that this page does not exhaustively list all Pre-made Voices and their respective voice_ids. For instance, I can't find 'Nicole' which is available under 'ELEVENLABS PREMADE' in the voices list of https://elevenlabs.io/speech-synthesis

It is also featured in many Marketing pages of the site https://elevenlabs.io/languages/french and https://elevenlabs.io/voice-cloning.

How to get its voice_id?

Thanks for your help,

**Comment by louisjoecodes** [comment]
Go to Voices in the sidebar, select the Library tab, search for "Nicole," click + Add, then navigate to My Voices, click View, and you’ll find the ID in the bottom-right corner.
