### ISSUE TITLE
Unable to parse csv. Required columns: speaker, start_time, end_time, transcription, translation.

### ISSUE THREAD

**Issue by allahverdiyevo** [elevenlabs/elevenlabs-docs#183]
I cannot do manual dubbing. I import video, audio and csv file, but receive the error "Unable to parse csv. Required columns: speaker, start_time, end_time, transcription, translation."
The CSV file is attached. What is wrong with it?
[rus test - Copy.txt](https://github.com/elevenlabs/elevenlabs-docs/files/14547521/rus.test.-.Copy.txt)

**Comment by justfortune** [comment]
Изображениspeaker,start_time,end_time,transcription,translation
Adam,"0:00:01,000","0:00:05,000","Hello, how are you?","Hola, ¿cómo estás?"
Adam,"0:00:06,000","0:00:10,000","I'm fine, thank you.","Estoy bien, gracias."
я

**Comment by louisjoecodes** [comment]
Thanks for the help @justfortune
