### ISSUE TITLE
Problème de payement 

### ISSUE THREAD

**Issue by xdftguhgf** [elevenlabs/elevenlabs-docs#19]
Bonjour,

J'ai récemment voulu prendre un abonnement,  mais ma carte ne fonctionne pas, alors que j'ai une carte visa qui peut faire des achats en ligne. 
J'aimerais avoir une réponse à mon problème.

Cordialement, 

Debosschere Florian

**Comment by Vexthecollector** [comment]
Github can't help with payment issues.
Reach out to general support here: https://help.elevenlabs.io/hc/en-us/requests/new
