### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by Scronkfink** [elevenlabs/elevenlabs-docs#217]
Path: /api-reference/add-voice

I wish elevenlabs specified what "files" was supposed to be. 

A string of "one or more audio files to clone the voice from" is an ambiguous definition.

**Comment by Scronkfink** [comment]
Yes, and the only reason I commented on this ambiguity is because I have been having a very troublesome time getting the "addVoice" API to work. 

I have been sending the raw binary data attached to the "files" key using fs.createReadStream(), but since I have still been incapable of successfully accessing this API using Node.js, I figured there was a chance you all might be expecting this Meta data represented in a json string or something, given that the docs do say it's expected as a string.

Appreciate the response...elevenLabs is awesome.

**Comment by marcelthomas5** [comment]
@Scronkfink Thanks again for posting this. Just to let you know that the docs have been updated.
