### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by Ldesiderio** [elevenlabs/elevenlabs-docs#244]
Path: /voices/voice-lab/professional-voice-cloning

It seems like the links on the bottom are not directing to what they meant.

[Audiobook (The Great Gatsby)](https://elevenlabs.io/docs/voice-lab/scripts/the-great-gatsby)
[News Article](https://elevenlabs.io/docs/voice-lab/scripts/news-article)
[Conversation](https://elevenlabs.io/docs/voice-lab/scripts/conversation)
[Radio Ad](https://elevenlabs.io/docs/voice-lab/scripts/radio-ad)

**Comment by louisjoecodes** [comment]
Fixed.
