### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by rosj2u** [elevenlabs/elevenlabs-docs#245]
Path: /speech-synthesis/voice-settings
I used the AI voicelab but when it gets half way the voice changes and keep going lower into robot sounds. I lost most of my characters everytime it does that. Can I get my characters reimbursed back to my quota because I couldn't use the voice due to error.

**Comment by louisjoecodes** [comment]
Hey @rosj2u could you please share steps to reproduce/example outputs?
