### ISSUE TITLE
Documentation is missing cost details for Dubbing Studio workflow

### ISSUE THREAD

**Issue by jrlanguage** [elevenlabs/elevenlabs-docs#247]
Path: /voiceover-studio/overview
Documentation does not provide details of the cost of a video dubbing studio project.

A typical project will include AI transcription + AI Translation + User editing of the translation in Studio + AI Text to Audio + Dubbing on the video.

We do not clearly understand the cost/minute for videos that would be processed this way.

Thanks,
Sergio

**Comment by louisjoecodes** [comment]
Hey! We have included further details around credit costs for the dubbing workflow:

---

Voiceover Studio does not deduct credits to create your initial project. Credits are deducted every time material is generated. Similar to Speech-Synthesis, credit costs for Voiceover Clips are based on the length of the text prompt. SFX clips will deduct 80 credits per generation.

If you choose to Dub (translate) your Voiceover Project into different languages, this will also cost additional credits depending on how much material needs to be generated. The cost is 1 credit per character for the translation, plus the cost of generating the new audio for the additional languages.
