### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by SalmunPhiscape** [elevenlabs/elevenlabs-docs#255]
Path: /api-reference/python-text-to-speech-guide

from elevenlabs import set_api_key
ImportError: cannot import name 'set_api_key' from 'elevenlabs'

**Comment by lharries** [comment]
Hi, those instructions were for an older version of the SDK. Please follow these instructions instead: http://localhost:3000/api-reference/how-to-use-tts-with-streaming I've updated the link in the docs to this instead
