### ISSUE TITLE
Add the posibility to create voices in French Canadian.

### ISSUE THREAD

**Issue by m10ust** [elevenlabs/elevenlabs-docs#26]
I saw French Canadian with the Canadian flag next to it one time in the third column in Speech Synthesis, and it was clickable. Now I don't see it anymore and I have a paid subscription. What is going on?

**Comment by louisjoecodes** [comment]
Head to the [Voice Library](https://elevenlabs.io/app/voice-library) and filter by French & accent.

![Screenshot 2024-10-21 at 09 19 20](https://github.com/user-attachments/assets/446f05ac-4f21-4e8d-bf02-948bf0449fb5)
