### ISSUE TITLE
Custom Voices?

### ISSUE THREAD

**Issue by collinboler** [elevenlabs/elevenlabs-docs#265]
I copied the ID for my custom voice but it didn't work. How do I find my custom voice ID? There used to be a way to do it in docs but it seems to be gone now. Thank you.

**Comment by louisjoecodes** [comment]
Hi @collinboler, click on the "View" button next to your custom voice, in the bottom right corner you should see a link to copy the ID.

**Comment by collinboler** [comment]
Thanks!
