### ISSUE TITLE
Can not sign into my paid account HELP

### ISSUE THREAD

**Issue by tj13580** [elevenlabs/elevenlabs-docs#270]
Path: /introduction?utm_source=brevo  

 I have been trying to sign into my account.  I forgot the password and have been trying to reset it but no email is being sent. I have copies of my charges from your company every month. I really really want to use my service that I am paying for. So I thought maybe I have the wrong email account assigned. I tried signing up for a free account using the email account I believe is the one I used to sign up with. The response from your company was....'it is in use'.  How can it be 'in use' when I can't even get into it.  HELP!!!!

**Comment by louisjoecodes** [comment]
Hi @tj13580 
Sorry you are experiencing this, hope this has been resolved. Please feel free to re-open!
