### ISSUE TITLE
Narration skipping words in pronounciation dictionary

### ISSUE THREAD

**Issue by DWX-o** [elevenlabs/elevenlabs-docs#283]
Hey, I hope somebody can help.

I've followed the format provided by 11Labs for the pronunciation dictionary, but for some reason, the narration is skipping the names/words altogether when generating the audio output.

For context, here is the lexicon:

<?xml version="1.0" encoding="UTF-8"?>
<lexicon version="1.0"
      xmlns="http://www.w3.org/2005/01/pronunciation-lexicon"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.w3.org/2005/01/pronunciation-lexicon
        http://www.w3.org/TR/2007/CR-pronunciation-lexicon-20071212/pls.xsd"
      alphabet="ipa" xml:lang="en-US">
    <lexeme>
        <grapheme>Alastar</grapheme>
        <phoneme>/ˈæ.lə.stɚ/</phoneme>
    </lexeme>
    <lexeme>
        <grapheme>Bjolan</grapheme>
        <phoneme>/ˈboʊ.lən/</phoneme>
    </lexeme>
    <lexeme>
        <grapheme>Cedric</grapheme>
        <phoneme>/ˈsiː.dɹək/</phoneme>
    </lexeme>
</lexicon>

**Comment by louisjoecodes** [comment]
Thanks for the support and suggestion @simonepstein
