### ISSUE TITLE
The generated Audio is missing the first few words

### ISSUE THREAD

**Issue by stumil000** [elevenlabs/elevenlabs-docs#299]
When we generate the audio from the transcript, it is omitting the first few words.
Is there an issue with ElevenLabs or is there a Setting we need to do in order to fix this issue?

**Comment by louisjoecodes** [comment]
Hi @stumil000, are you still experiencing this issue? Please provide steps to reproduce and we will take a look. Feel free to re-open. Thank you!

**Comment by stumil000** [comment]
Hi
It's been quite a while since logging this ticket and a response.
Anyhow, for your interest, it turn's out that the 'missing sound issue' I experienced was caused by my new 'wireless' headphones.
Yes that's right, when I swapped back to my previous old USB cabled in headphones everything was fine.
You can Google it if you need to.
It's an interesting one that might be worth a mention on an FAQ page.
Can I just say that I think that your software is fantastic!.
Kind regards
Stu

**Comment by louisjoecodes** [comment]
That is great, happy to hear that this has been resolved. Thank you for the kind words!
