### ISSUE TITLE
Issue on docs: websockets example

### ISSUE THREAD

**Issue by marcowang01** [elevenlabs/elevenlabs-docs#30]
Path: /api-reference/text-to-speech-websockets

Copied the end-to-end example for python websockets, put in my own api-keys + voice ID and the code just gets stuck on the first line  ` response = await websocket.recv()` and awaits forever.

**Comment by ikequan** [comment]
Make sure the input text ends with a space 
incorrect
text =  "Hello world"
correct:
text =  "Hello world "

**Comment by marcowang01** [comment]
Yea I have that. My code is copied exactly from the docs

**Comment by ajar98** [comment]
+1 this happens to me as well
