### ISSUE TITLE
Issue on docs : i am not able to access the voice , even though it is added in my voice library, and also shows up on the list of voices.

### ISSUE THREAD

**Issue by momoeyes22** [elevenlabs/elevenlabs-docs#309]
Path: /speech-synthesis/voice-selection
name='Shrey - Deep & Engaging ', description='A deep engaging Indian male voice. Sounds rich and resonates from within the chest and throat. The pitch is low, almost like a pleasantly rumbling hum that you can feel as much as you hear. Suitable for conversations.', labels={'use_case': 'conversational', 'accent': 'indian', 'descriptive': 'confident', 'age': 'middle_aged', 'gender': 'male', 'language': 'en'}, review_status='not_requested', review_message=None, enabled_in_library=False, instagram_username=None, twitter_username=None, youtube_username=None, tiktok_username=None, image_url=''), high_quality_base_model_ids=['eleven_turbo_v2', 'eleven_multilingual_v2'], safety_control=None, voice_verification=VoiceVerificationResponse(requires_verification=False, is_verified=False, verification_failures=[], verification_attempts_count=0, language=None, verification_attempts=None), owner_id='uRPdcjkUrwTRg9rPi1t24LossOZ2', permission_on_resource='admin')

**Comment by louisjoecodes** [comment]
Hi could you clarify and re-open this issue please?
