### ISSUE TITLE
May I ask if there is an API provided for authorized users to register and log in, or through Google authorization, but how can I call back to Elevenlabs to log in

### ISSUE THREAD

**Issue by 798499028** [elevenlabs/elevenlabs-docs#312]
May I ask if there is an API provided for authorized users to register and log in, or through Google authorization, but how can I call back to Elevenlabs to log in

**Comment by lharries** [comment]
Hi, there isn't an API to login, instead you can login via the UI then create an API for authenticating requests

https://help.elevenlabs.io/hc/en-us/articles/14599447207697-How-to-authorize-yourself-using-your-xi-api-key#:~:text=In%20order%20to%20use%20our,%22Profile%20%2B%20API%20key%22.
