### ISSUE TITLE
Is there an API available for user authorization, or is it authorized through Google, and how can I call back to Elevenlabs to log in?

### ISSUE THREAD

**Issue by 798499028** [elevenlabs/elevenlabs-docs#313]
Is there an API available for user authorization, or is it authorized through Google, and how can I call back to Elevenlabs to log in?

**Comment by lharries** [comment]
Hi, there isn't an API to login, instead you can login via the UI then create an API for authenticating requests

https://help.elevenlabs.io/hc/en-us/articles/14599447207697-How-to-authorize-yourself-using-your-xi-api-key#:~:text=In%20order%20to%20use%20our,%22Profile%20%2B%20API%20key%22.
