### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by fredcalmon** [elevenlabs/elevenlabs-docs#327]
Path: /api-reference/how-to-dub-a-video

module 'elevenlabs.dubbing' has no attribute 'dub_a_video_or_an_audio_file'

**Comment by louisjoecodes** [comment]
Hey @fredcalmon, please make sure you are on the latest version of the elevenlabs-python SDK. 

Should be version `1.9.0` or above


![Screenshot 2024-10-21 at 14 04 17](https://github.com/user-attachments/assets/f9eb3184-6c90-4534-8144-6d12cf6eb4ca)
