### ISSUE TITLE
Prompting emotion without having the prompt read aloud?

### ISSUE THREAD

**Issue by contentfree** [elevenlabs/elevenlabs-docs#33]
Path: /speech-synthesis/prompting

The AI generates text well when prompted but the prompting text is included in the output. How does one prompt a particular emotion without having "he shouted angrily" in the output? Is there any kind of hidden markup that can be used?

**Comment by louisjoecodes** [comment]
Hey! - The AI can sometimes infer the intended emotion from the text's context. Unfortunately at the moment there is no markup control for emotion.
https://elevenlabs.io/docs/speech-synthesis/prompting#emotion

**Comment by contentfree** [comment]
@louisjoecodes Not sure why this was closed as completed. Can it be left as open until the time when it can be addressed? Controlling the speech with markup is VERY important to some of us.
