### ISSUE TITLE
emphasis

### ISSUE THREAD

**Issue by slavopotam** [elevenlabs/elevenlabs-docs#34]
Is there any kind emphasis control? what i need to do to correct mistake in emphasis of the word?

**Comment by alertNiKole** [comment]
I too am having this issue with words that are spelled the same but pronounced differently such as present (gift) and present (presence, in attendance)

I could go with "preeesent" but I don't that with her voice.

A possible fix to introduce this type of adjustment would be to incorporate a dictionary integration. Allow the user to choose which definition they intended to use, then the correct enunciation of the word be integrated on regeneration.

Example: 
 "that always present@2 effort to shield yourself from both the wind, the wet-cold and the beggared & hungry as you leaped into your Lyft or hopped into the closest metro. "

**Comment by louisjoecodes** [comment]
https://elevenlabs.io/docs/speech-synthesis/prompting
