### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by cyenis** [elevenlabs/elevenlabs-docs#341]
Path: /audio-native/wordpress

Failed to load resource: the server responded with a status of 401 ()
8427352.js:44 Ip2c error: lookup failed. Returned status of 401
b.onreadystatechange @ 8427352.js:44
api.elevenlabs.io/v1/audio-native/2291b6138dfd5cfc6ba564ebd9a8a9e2053064834819b8e9cbdfecaebd396d21/convert:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
index-ny8ORC-n.js:9 [AudioNative] Cannot read properties of undefined (reading 'message')
C @ index-ny8ORC-n.js:9

**Comment by louisjoecodes** [comment]
Hi @cyenis please provide more details and re-open this ticket please. Thank you.
