### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by ssujjy** [elevenlabs/elevenlabs-docs#354]
Path: /introduction

hello.
 
I want to use AI Isorator to create “a fairy tale read by mom and dad” with Flutter. 

You are logged in and registered with your Google account. But I can't see the API key where my revision is. 

I would like to receive guidance on how to obtain an API key and use it to develop with Flutter.

I hope to receive an answer as soon as possible.  

thank you.

**Comment by louisjoecodes** [comment]
Hello! We have many guides in our documentation. I'd recommend checking out a few video tutorials on youtube for a more step-by-step introduction.

https://elevenlabs.io/docs/api-reference/getting-started
