### ISSUE TITLE
Error in Uploading Voice File Using API

### ISSUE THREAD

**Issue by aditimishra23** [elevenlabs/elevenlabs-docs#363]
Path: [/api-reference/add-voice](https://elevenlabs.io/docs/api-reference/add-voice)
API is not working. I am getting below error:
{"detail":[{"loc":["body","files",0],"msg":"Expected UploadFile, received: <class 'str'>","type":"value_error"}]}

**Comment by louisjoecodes** [comment]
Hey @aditimishra23, please provide more details. Closing this issue for now/
