### ISSUE TITLE
How to fix added pauses in speech?

### ISSUE THREAD

**Issue by hospod** [elevenlabs/elevenlabs-docs#378]
I recently converted my family memoir to an audiobook read by my cloned voice. In some places in the spoken version, there are pauses between words where spaces/pauses do not exist in my manuscript. Is there a way to fix this or prevent it if I reconvert it?

**Comment by louisjoecodes** [comment]
Hi @hospod, perhaps our [prompting guide](https://elevenlabs.io/docs/speech-synthesis/prompting) will help with this?
