### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by ppicazo1** [elevenlabs/elevenlabs-docs#388]
Path: /api-reference/streaming

I cannot get any of the examples to put out any sound  I tried the one below and various others like the Getting Started one and the voice list one.   I am signed up for the 5.00 plan as I am just out to learn at this time.  Using python.  I replaced the YOUR_API_KEY  with my relatively large API Key but I hear nothing or I get errors depending on which code I am trying.   I am using Python 3.12.3.   Also, what is the difference between the XI_API_KEY and the API_KEY?   Is the XI_API_KEY the name given for the key?

from elevenlabs import VoiceSettings
from elevenlabs.client import ElevenLabs

client = ElevenLabs(
    api_key="YOUR_API_KEY",
)
client.text_to_speech.convert_as_stream(
    voice_id="pMsXgVXv3BLzUgSXRplE",
    optimize_streaming_latency="0",
    output_format="mp3_22050_32",
    text="It sure does, Jackie… My mama always said: “In Carolina, the air's so thick you can wear it!”",
    voice_settings=VoiceSettings(
        stability=0.1,
        similarity_boost=0.3,
        style=0.2,
    ),
)

**Comment by louisjoecodes** [comment]
Hi @ppicazo1,

Here is a simpler example which should play:

```python
import { ElevenLabsClient, play } from "elevenlabs";

const elevenlabs = new ElevenLabsClient({
    apiKey: "YOUR_API_KEY", // Defaults to process.env.ELEVENLABS_API_KEY
});

const audio = await elevenlabs.generate({
    voice: "Sarah",
    text: "Hello! 你好! Hola! नमस्ते! Bonjour! こんにちは! مرحبا! 안녕하세요! Ciao! Cześć! Привіт! வணக்கம்!",
    model_id: "eleven_multilingual_v2",
});

await play(audio);
```

In the SDK we expose a 'play' function which interacts with MPV/ffmpeg in your CLI and plays the sound on your machine.
