### ISSUE TITLE
not clear splaing

### ISSUE THREAD

**Issue by raihankb** [elevenlabs/elevenlabs-docs#389]
I have been facing this problem for a long time.  So I need a solution, sometimes I can't get the audio output nicely.  AI speaks a lot of mistakes and in some places it says loudly and in some places it says slowly, now it is seen that the first part is speaking according to the tune and the last part is speaking in a very slow tune.  Sometimes it is seen that one voice over changes to another voice over.  So I hope to get this problem resolved soon.  I have lost a lot of credit due to this problem.

![Screenshot_54](https://github.com/user-attachments/assets/b3dbc1da-a81f-4ca2-b246-0b02215f4a5a)

**Comment by louisjoecodes** [comment]
Hi there, sorry you are experiencing this - please check out our [prompting guide](https://elevenlabs.io/docs/speech-synthesis/prompting) for identifiers like XV275K, it might be worth adding spaces i.e. X V 2 7 5 K
