### ISSUE TITLE
Issue on docs: isFinal flag is null instead of true or false

### ISSUE THREAD

**Issue by axcasella** [elevenlabs/elevenlabs-docs#405]
We are using websocket text to speech and noticed that the isFinal flag is always null, (instead of true or false). We have not been able to get a non-null response. 

https://elevenlabs.io/docs/api-reference/websockets#streaming-output-audio

<img width="776" alt="Screenshot 2024-09-30 at 1 38 42 PM" src="https://github.com/user-attachments/assets/4e2df125-8c92-444a-bc6e-73323fbda5f2">

Please advise.

**Comment by robbie-anam** [comment]
I also have this issue, even after sending a flush command

**Comment by louisjoecodes** [comment]
Hello folks - checking.

**Comment by louisjoecodes** [comment]
To receive an `isFinal` true flag from the Websocket, you need to send a close connection message.

```
{
    "text": ""
}
```

Documentation: https://elevenlabs.io/docs/api-reference/websockets

**Comment by jtmuller5** [comment]
You have to close the websocket to get an isFinal flag? That doesn't make sense.

I mainly need to know if all of the text I sent is finished generating. Sometimes I get responses on the websocket that are only parts of the full text. In that case, I would like to see isFinal = false on the audio pieces and then isFinal = true after the last piece has been received.
