### ISSUE TITLE
Problems with voice generation

### ISSUE THREAD

**Issue by jangsikyung** [elevenlabs/elevenlabs-docs#427]
Path: /voices/voice-lab/professional-voice-cloning

I uploaded a recording now to add voice.
However, the service is not available due to 5 inconsistencies in the voice verification stage.
Please let me know if you can solve this problem or how I can solve it.
I'm behind on urgent tasks right now, so I want a quick solution.

**Comment by louisjoecodes** [comment]
Hi @jangsikyung, could you please contact our support team who would be happy to help: https://help.elevenlabs.io/hc/en-us/articles/14139492797073-How-can-I-contact-support
