### ISSUE TITLE
Voice library management a real pain 

### ISSUE THREAD

**Issue by capefinn** [elevenlabs/elevenlabs-docs#447]
Path: /guides/voices
I just wanted to say that having the voice librbary only be able to have 30 voices is really constricting and requires constatn unnecessary management.
If you are voice casting for a project and you are translating the original into 14 plus languages and for each langiuage you want to give your client three options its already an issue, then if you consider that you might have several projects with this situation it creates chaos.
Its the worst feature of elevenlabs and a real problem.

**Comment by louisjoecodes** [comment]
Hey! Thanks a lot for reaching out. The following article explains the maximum number of custom voices per tier:
https://help.elevenlabs.io/hc/en-us/articles/24351056337937-How-many-voice-slots-do-I-get-per-tier-and-how-can-I-increase-it
