### ISSUE TITLE
Issue: Project | Versions Ordered Listing

### ISSUE THREAD

**Issue by alertNiKole** [elevenlabs/elevenlabs-docs#45]
Path: /projects/overview/

There appears to be an issue the order within Projects, versions.  Upon conversion, the order is out of order by generation (its not chronological). 

Fields Shown:
Versions
Title
##
Play
Download

The issue is the order shown is 47, 33, 25,  44, 26 (not as rendered by time)

Upon pressing play each shows the same (most recent) created timestamp rather than the actual time of generation.

Download - appears to also be malfunctioning as no downloads render from this pop up screen but are available after clicking play at the bottom. (no download renders from chapter, convert, download, post chapter conversion)

Please also update documentation to discuss this screen/versions within chapters/projects

![image](https://github.com/elevenlabs/elevenlabs-docs/assets/28637298/20b4ae02-7f5e-486b-8670-273c530fb14a)

**Comment by louisjoecodes** [comment]
Thanks for flagging this. We are working on changes to the projects view, once launched this will be resolved. Thanks!
