### ISSUE TITLE
Not able to sign in to my paid account. says error and sometimes says acc deleted , 

### ISSUE THREAD

**Issue by Aabhishek-dev** [elevenlabs/elevenlabs-docs#466]
I have a paid account on eleven labs and i am unable to login into it , it shows error" Unable to login with google.com due to: Firebase: HTTP Cloud Function returned an error: {"error":{"message":"Your account has been deleted.","status":"PERMISSION_DENIED"}} (auth/internal-error)." when i tried to login using any of my google acc just in case i thought maybe it was another account. moreover i tried resseting password though that would solve issue, surprisingly password reset mail arrise and i reset pasword, still cant loging. This time it says "Account deleted" wtf. aklways so glitchy. aabhish45@gmail.com

**Comment by louisjoecodes** [comment]
Hey! This sounds like a problem - please contact our support here: https://help.elevenlabs.io/
