### ISSUE TITLE
Love the service, but hate your subscription model

### ISSUE THREAD

**Issue by wickwood** [elevenlabs/elevenlabs-docs#494]
Hello,

Not sure where to post this except here because everything I click on for support leads back this GitHub forum.

I just wanted to say I feel really trapped in your subscription model and I really hate it.

When I first started using Elevenlabs a few month ago, I quickly went over the allowed credits and had to upgrade to your Pro level to complete my project on time.  But now if I downgrade, I will lose all my accumulated credits that I have already paid for.

Feels like an awful cell phone plan from the 1990's!

Why can't we downgrade and keep the credits we already paid for?

Like I said in the title, I love your service, but I hate your subscription model.  

If I find a another service that can do what I need it to do and has a better subscription model, I will have no other choice but to leave because I keep getting more credits that I can't use and now I just learned you also cap the number of credits that rollover.

REALLY! Are you freaking kidding me? Do you not like your subscribers that much?

Please reconsider this pricing model.  There must be something that works for both you and your subscribers.

Thanks for letting me vent and hope you truly consider changing things because I really don't want to leave, but I can't stand this.

**Comment by louisjoecodes** [comment]
Hey! Please use our support link [here](https://help.elevenlabs.io/hc/en-us/articles/14139492797073-How-can-I-contact-support)
