### ISSUE TITLE
Number is not being said the way it is written

### ISSUE THREAD

**Issue by wickwood** [elevenlabs/elevenlabs-docs#550]
Hello,

I'm using the Voice Over Studio and discovered that for some reason a part of my script that as following text:

> And that could be savings to the employer of about forty-five hundred dollars annually for every 10 employees.

Is being said as four thousand five hundred dollars.

In the past it was said exactly as I had written it.

I prefer that it say, "forty-five hundred dollars" because that's how I talk.

**Comment by louisjoecodes** [comment]
Could you try creating a pronunciation dictionary for this?

**Comment by wickwood** [comment]
Sorry I never saw this response.  

I also don't know how to create a pronunciation dictionary.

The weird thing about it is that the issue is that it is not consistent.  In the same project i can have the same text and it can be said 2 different ways.  

One would expect that if the text is "forty-five hundred dollars" that would be what is spoken, not "four thousand five hundred dollars".  In fact, I was quite surprised that it even recognized those 2 things as being the same.

**Comment by wickwood** [comment]
P.S. I will look for information on creating a create a pronunciation dictionary.  Thanks for the suggestion.
