### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by burnleydave** [elevenlabs/elevenlabs-docs#551]
Path: /conversational-ai/docs/introduction
Hi there. I have tried using your API and Agent ID as in the guide, but in Web apps, no Chat widget appears. I have tried building in Loveable AI, Bolt. new and Pico Metagpt.
I am using this code snippet:
# Your ElevenLabs agent number and WebSocket URL
ELEVENLABS_AGENT_ID = '4ihly4iY3vAoBEv1uhSj' 
ELEVENLABS_WS_URL = f'wss://api.elevenlabs.io/v1/convai/conversation?agent_id={ELEVENLABS_AGENT_ID}'

**Comment by louisjoecodes** [comment]
Hi - In our dashboard you should be able to get a widget for this which you will be able to embed in your website.
