### ISSUE TITLE
Conversational AI API - OpenAI Assistant

### ISSUE THREAD

**Issue by TheGreenGear** [elevenlabs/elevenlabs-docs#560]
Path: /conversational-ai/docs/introduction

I am having an issue with connecting the Eleven Labs Conversational AI with my OpenAI Assistant AI. Can you please provide detail to assist such as the Server URL for OpenAI Assistant, and the steps to make the connection. 

Thanks
T

**Comment by louisjoecodes** [comment]
Hello @TheGreenGear could you please share details about your set-up? Agent config, SDK & examples please.

**Comment by TheGreenGear** [comment]
Hi, 
Thanks for the quick response. I’m attempting to connect the new Eleven Labs Conversational AI to my OpenAI Assistant as the Knowledge Bases, however I’m having issues when I test. In the conversational AI, I’ve selected Custom LLM. Can you please confirm if the Server URL to utilize the OpenAI Assistant API is: https://api.openai.com/v1/chat/completions

Thanks

**Comment by TheGreenGear** [comment]
No worries, I was able to use a web hook and it works. 

Thanks

**Comment by TheGreenGear** [comment]
Hello, 
Sorry that I misspoke, as the web hook did not work correctly. Is there any type of documentation to support the api from the Eleven Labs Conversational AI to my OpenAI Assistant API so that I can use the OpenAI Assistant as my knowledge base? 

Thanks

**Comment by louisjoecodes** [comment]
Hi @TheGreenGear - we have recently fixed the issue with Custom LLMs. Hopefully this is now working smoothly for you.

Kind regards,
Louis
