### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by tpk213** [elevenlabs/elevenlabs-docs#569]
Path: /conversational-ai/customization/conversation-configuration

I tried this. But I am not getting the responses printed in the console. I am using the python example. The latency info is getting printed though. 

       callback_agent_response=lambda response: print(f"Agent: {response}"),
        callback_agent_response_correction=lambda original, corrected: print(f"Agent: {original} -> {corrected}"),
        callback_user_transcript=lambda transcript: print(f"User: {transcript}"),
aallback_latency_measurement=lambda latency: print(f"Latency: {latency}ms"),

**Comment by louisjoecodes** [comment]
Hi! Please make sure you have the correct client events enabled in the Conversational AI agent dashboard
