### ISSUE TITLE
dubbing studio export help needed

### ISSUE THREAD

**Issue by SDPFM** [elevenlabs/elevenlabs-docs#575]
Path: /product/dubbing/studio
Hello Team,
I am currently working on a dubbing project namely Nora animation German. There are few things I notice that I currently need help on. Though there are few suggestions for improvements that I'll mention later.
Need help on-
1. The exported .aaf file does not have same VO as selected in my dubbing project . please help
2. Even after refreshing the stale audio clip , the new VO settings are not applied to it. How to ensure that track settings are applied to all the clips in the track.
3. Unable to see the VO , in the dropdown list ,that I want to use. 
looking forward to your help asap.
Link to my project -
[https://elevenlabs.io/v1/dubbing/OgBm63KNt1y83aP6fUGG](url)
Regards,
Shruti Daga
Video Editor
Pocket FM

**Comment by louisjoecodes** [comment]
Hey, thanks for your question. For workflow-specific questions please contact support: 
https://help.elevenlabs.io/hc/en-us/articles/14139492797073-How-can-I-contact-support
