### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by adastraSoftware** [elevenlabs/elevenlabs-docs#59]
Path: /voicelab/instant-voice-cloning

Hello ElevenLabs Technical Team,

I am planning to use your ElevenLabs platform for voice cloning processes. In this context, I have some uncertainties and need your assistance.

Specifically, I want to perform voice cloning by reading Turkish texts. Is there any issue with my provided voice samples being in Turkish for the cloning process? Once the cloning process is completed, I plan to use this cloned voice to narrate Turkish texts. Do you have any restrictions or recommendations regarding this on your platform?

 

Thank you,

**Comment by Vexthecollector** [comment]
These kind of questions are best answered by the general support here: https://help.elevenlabs.io/hc/en-us/requests/new
