### ISSUE TITLE
[Feature] Create a Vue Streaming Component like Your React Streaming Component

### ISSUE THREAD

**Issue by dosstx** [elevenlabs/elevenlabs-docs#65]
I see there is a React Streaming Component: https://docs.elevenlabs.io/api-reference/full-guides/react-guide#using-audiostream-react-component

Would be nice to make a version for Vue as not everyone is using React. There is complexity in using streaming and a component such as that would make it much easier to work with speech to streaming in Vue apps. Thanks!

**Comment by Vexthecollector** [comment]
Currently we do not have anyone working closely with Vue that could write this article. 

We'll add more Guides when we can, but no guarantee that we will add Vue Specifically.
