### ISSUE TITLE
Selecting "audiobooks" hyperlink links to incorrect page?

### ISSUE THREAD

**Issue by RamanSB** [elevenlabs/elevenlabs-docs#68]
On the [introduction page](https://docs.elevenlabs.io/welcome/introduction) when selecting the dataset "audiobooks" we are taken to the "projects" page, I believe we were supposed to linked to some audio based dataset instead that the model was trained with?

![11labs-doc-intro](https://github.com/elevenlabs/elevenlabs-docs/assets/13969478/57e3bef1-a3e5-4e28-8905-3b338ffc46d4)

**Comment by Vexthecollector** [comment]
This is currently correct. Projects is there for you to create your own audiobooks. It allows for easy import of many different formats to create a rather simple solution to create your audiobook.

We do not have any audiobook library as of now. Though I understand this can be a bit confusing.
